# Simplified version from https://docs.dagster.io/deployment/oss/deployment-options/docker

services:
  # This service runs the gRPC server that loads your user code, in both dagster-webserver
  # and dagster-daemon. By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the
  # run launcher to use this same image when launching runs in a new container as well.
  # Multiple containers like this can be deployed separately - each just needs to run on
  # its own port, and have its own entry in the workspace.yaml file that's loaded by the
  # webserver.
  dagster_user_code:
    build:
      context: ./dagster/
      dockerfile: ./Dockerfile
    container_name: dagster_user_code
    image: dagster_user_code_image
    restart: always
    environment:
      DAGSTER_HOME: ${DAGSTER_HOME}
      DAGSTER_CURRENT_IMAGE: 'dagster_user_code_image'
      DATABASE_URL: ${DATABASE_URL}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_USER: ${SERVER_USER}
    volumes:
      - dagster_home:${DAGSTER_HOME}
      - ${SSH_PRIVATE_KEY_PATH}:/root/.ssh/dagster_pmtiles:ro
    networks:
      - internal
    healthcheck:
      test: ["CMD", "dagster", "api", "grpc-health-check", "-p", "4000"]
      interval: 3s
      timeout: 1s
      retries: 20
      start_period: 3s

  # This service runs dagster-webserver, which loads your user code from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from the webserver will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  dagtser_webserver:
    build:
      context: ./docker/
      dockerfile: ./Dockerfile
      args:
        - DAGSTER_HOME=${DAGSTER_HOME}
    entrypoint:
      - dagster-webserver
      - -h
      - '0.0.0.0'
      - -p
      - '3000'
      - -w
      - workspace.yaml
    container_name: dagtser_webserver
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - dagster_home:${DAGSTER_HOME}
    networks:
      - internal
    depends_on:
      dagster_user_code:
        condition: service_healthy

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  dagster_daemon:
    build:
      context: ./docker/
      dockerfile: ./Dockerfile
      args:
        - DAGSTER_HOME=${DAGSTER_HOME}
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    volumes: 
      - dagster_home:${DAGSTER_HOME}
    networks:
      - internal
    depends_on:
      dagster_user_code:
        condition: service_healthy

networks:
  internal:
    driver: bridge
    name: internal
  
volumes:
  dagster_home:
