services:
  web:
    build:
      context: ./15-minute-cities
      dockerfile: Dockerfile
    env_file:
      - ./15-minute-cities/.env
    restart: unless-stopped
    depends_on:
      - tileserv
    ports:
      - "3000:3000"

  tileserv:
    image: pramsey/pg_tileserv:latest
    env_file:
      - ./15-minute-cities/.env
    restart: unless-stopped
    ports:
      - "7800:7800"